[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "build/"
  
  # Environment variables for build
  [build.environment]
    CI = "false"
    GENERATE_SOURCEMAP = "false"

# Handle React Router for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 🔒 ENTERPRISE SECURITY HEADERS - Comprehensive Protection
[[headers]]
  for = "/*"
  [headers.values]
    # 🔒 Content Security Policy - Prevent XSS and injection attacks
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://checkout.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' https://api.stripe.com https://checkout.stripe.com https://plausible.io; object-src 'none'; base-uri 'self'; form-action 'self' https://checkout.stripe.com; frame-ancestors 'none'; upgrade-insecure-requests"
    
    # 🔒 Frame Protection - Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # 🔒 XSS Protection - Browser XSS filtering
    X-XSS-Protection = "1; mode=block"
    
    # 🔒 Content Type Protection - Prevent MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # 🔒 Referrer Policy - Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 🔒 HSTS - Force HTTPS connections
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # 🔒 Permissions Policy - Control browser features
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=(), accelerometer=(), gyroscope=(), magnetometer=(), ambient-light-sensor=()"
    
    # 🔒 Cross-Origin Policies - Isolate origin
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    
    # 🔒 Security Headers - Additional protection
    X-Permitted-Cross-Domain-Policies = "none"
    X-Download-Options = "noopen"
    X-DNS-Prefetch-Control = "off"
    
    # 🔒 Cache Control - Default caching
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 