[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "python3", "gcc", "gnumake", "postgresql", "pkg-config", "openssl", "zlib", "libpng", "libjpeg", "giflib", "librsvg", "vips", "tesseract"]

[phases.install]
cmds = ["cd backend && npm ci --only=production --verbose"]

[phases.build]
cmds = ["echo 'No build step needed for backend'"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PYTHON = "python3"
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
SHARP_FORCE_GLOBAL_LIBVIPS = "false"
npm_config_build_from_source = "true" 