[build]
# Build command for backend
command = "cd backend && npm install"

# Working directory
workdir = "backend"

# Environment variables for build
[build.environment]
  NODE_VERSION = "20"

# Production environment configuration
[deploy]
  startCommand = "cd backend && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

# Resource allocation
[deploy.resources]
  cpu = 1000
  memory = 1024
  disk = 2048

# Scaling configuration
[deploy.scaling]
  min = 1
  max = 5
  target_cpu = 80

# Environment variables
[env]
  NODE_ENV = "production"
  PORT = "${{RAILWAY_PUBLIC_PORT}}"

# Service configuration for backend API
[[services]]
  internal_port = "${{PORT}}"
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = "${{PORT}}"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443" 